version: 0.2

env:
  variables:
    build_version: "19.7"

phases:
install:
    runtime-versions:
        java: corretto8
  pre_build:
    commands:
      - echo "Copying files to tomcat folder"
      - mkdir -p ./tomcat-$build_version/
      - cp -r scripts ./tomcat-$build_version/
      - cp appspec.yml ./tomcat-$build_version/
      - cp index.html ./tomcat-$build_version/
  build:
    commands:
      - echo "Building the tar"
      - tar -czf ./tomcat-$build_version.tgz ./tomcat-$build_version/
artifacts:
  files:
    - tomcat-*.tgz
