version: 0.2

phases:
  pre_build:
    commands:
      - echo "Copying files to tomcat folder"
      - mkdir -p ./tomcat/
      - cp -r scripts ./tomcat/
      - cp index.html ./tomcat/
  build:
    commands:
      - echo "Building the tar"
    #  - zip ./tomcat.zip ./tomcat/scripts/* ./tomcat/index.html appspec.yml
artifacts:
  files:
     - tomcat/**/*
