version: 0.2

env:
  variables:
    build_version: "19.7"

phases:
  pre_build:
    commands:
      - echo "Copying files to tomcat folder"
      - mkdir -p ./tomcat-$build_version/
      - cp -r scripts ./tomcat-$build_version/
      - cp index.html ./tomcat-$build_version/
  build:
    commands:
      - echo "Building the tar"
      - zip ./tomcat-$build_version.zip ./tomcat-$build_version/ appspec.yml
artifacts:
  files:
    - tomcat-*.zip
