version: 0.2

phases:
  pre_build:
    commands:
      - echo "Copying files to tomcat folder"
      - mkdir -p ./tomcat/
  build:
    commands:
      - echo "Building the tar"
      - cp -r scripts ./tomcat/
      - cp index.html ./tomcat/
artifacts:
  files:
     - tomcat/**/*
     - appspec.yml
